### ISSUE TITLE
Tìm input, output node name

### ISSUE THREAD

**Issue by phuhung273** [phamvanhanh6720/IDCardVNRecognition#3]
Chào bạn, bạn có thể cho mình hỏi 1 câu hơi ngoài lề một chút: Làm sao để tìm ra input và output node name khi gọi tf serving ?

Ví dụ như trong repo của bạn có sử dụng `request.inputs["input_1"]`  và `result = result.outputs["tf_op_layer_concat_14"].float_val`

Mình có thử dùng tool Netron nhưng chỉ tìm được input.

Cám ơn các bạn rất nhiều.

**Comment by 1653134** [comment]
Anh chạy Demo được ko ạ!Em chạy bị lỗi ở issue ở trên á.

**Comment by phuhung273** [comment]
@1653134 bạn chụp thử error đi

**Comment by 1653134** [comment]
[cid:73394b88-1f9e-498d-a6de-3fc684e700cb]
Dạ như này anh ạ!
________________________________
Từ: Hung Tran <notifications@github.com>
Đã gửi: 13 Tháng Mười 2020 11:56 SA
Đến: phamvanhanh6720/IDCardVNRecognition <IDCardVNRecognition@noreply.github.com>
Cc: LÊ TẤN PHONG <1653134@student.hcmus.edu.vn>; Mention <mention@noreply.github.com>
Chủ đề: Re: [phamvanhanh6720/IDCardVNRecognition] Tìm input, output node name (#3)


@1653134<https://github.com/1653134> bạn chụp thử error đi

**Comment by 1653134** [comment]
![image](https://user-images.githubusercontent.com/46516057/95832010-f481c200-0d63-11eb-8c79-8aeaada0de7b.png)
Em bị thêm cái này nữa

**Comment by phuhung273** [comment]
Project này ngoài backend còn có chạy một tensorflow_model_server nữa. Error của bạn là backend gọi rpc đến nhưng ko có server model.
Như ở hướng dẫn là chạy trên ubuntu, bạn chạy trên win thì tìm hiểu thử Tensorflow Serving trên Docker nha.

**Comment by 1653134** [comment]
Dạ cảm ơn ạ!

________________________________
Từ: Hung Tran <notifications@github.com>
Đã gửi: 13 Tháng Mười 2020 3:39 CH
Đến: phamvanhanh6720/IDCardVNRecognition <IDCardVNRecognition@noreply.github.com>
Cc: LÊ TẤN PHONG <1653134@student.hcmus.edu.vn>; Mention <mention@noreply.github.com>
Chủ đề: Re: [phamvanhanh6720/IDCardVNRecognition] Tìm input, output node name (#3)


Project này ngoài backend còn có chạy một tensorflow_model_server nữa. Error của bạn là backend gọi rpc đến nhưng ko có server model.
Như ở hướng dẫn là chạy trên ubuntu, bạn chạy trên win thì tìm hiểu thử Tensorflow Serving trên Docker nha.

**Comment by phamvanhanh6720** [comment]
> Project này ngoài backend còn có chạy một tensorflow_model_server nữa. Error của bạn là backend gọi rpc đến nhưng ko có server model.
> Như ở hướng dẫn là chạy trên ubuntu, bạn chạy trên win thì tìm hiểu thử Tensorflow Serving trên Docker nha.

**Comment by phamvanhanh6720** [comment]
> Chào bạn, bạn có thể cho mình hỏi 1 câu hơi ngoài lề một chút: Làm sao để tìm ra input và output node name khi gọi tf serving ?
> 
> Ví dụ như trong repo của bạn có sử dụng `request.inputs["input_1"]` và `result = result.outputs["tf_op_layer_concat_14"].float_val`
> 
> Mình có thử dùng tool Netron nhưng chỉ tìm được input.
> 
> Cám ơn các bạn rất nhiều.

Cái này mình convert weight từ darknet -> tensorflow nên mình hiểu được output của nó là gì. Bạn muốn tìm chi tiết thì có thể xem trong save_model.py
