### ISSUE TITLE
Lỗi khi chạy Demo

### ISSUE THREAD

**Issue by 1653134** [phamvanhanh6720/IDCardVNRecognition#4]
Em tải về chạy thử thì nó ra lỗi này. Em xin cách khắc phục ạ!

D:\Downloads\IDCardVNRecognition-master>python run.py
ENV is set to: production
2020-10-13 10:42:50.586144: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
File exists: C:\Users\VBD\.cache/gdown\https-COLON--SLASH--SLASH-drive.google.com-SLASH-uc-QUESTION-export-EQUAL-download&id-EQUAL-1-olev206xLgXYf7rnwHrcZLxxLg5rs0p
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from app import app
  File "D:\Downloads\IDCardVNRecognition-master\app\__init__.py", line 10, in <module>
    from app import main
  File "D:\Downloads\IDCardVNRecognition-master\app\main.py", line 33, in <module>
    reader = Predictor(config)
  File "D:\Downloads\IDCardVNRecognition-master\reader\reader.py", line 22, in __init__
    model.load_state_dict(torch.load(weights, map_location=torch.device(device)))
  File "C:\Users\VBD\AppData\Roaming\Python\Python37\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VietOCR:
        size mismatch for transformer.embed_tgt.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256]).
        size mismatch for transformer.fc.weight: copying a param with shape torch.Size([232, 256]) from checkpoint, the shape in current model is torch.Size([233, 256]).
        size mismatch for transformer.fc.bias: copying a param with shape torch.Size([232]) from checkpoint, the shape in current model is torch.Size([233]).

**Comment by phuhung273** [comment]
- Package vietocr phải dùng đúng version 0.1.9
- Chỉ có model vgg_transformer: `config = Cfg.load_config_from_name('vgg_transformer')`

**Comment by 1653134** [comment]
Em cố load model đã train không dùng qua Tensorflow_Serving nhưng bị lỗi.

"""Code"""
model_crop = tf.keras.models.load_model('models\\detector\\1')
filepath =filename
img, original_image, original_width, original_height = preprocess_image(filepath, Cropper.TARGET_SIZE)

if img.ndim == 3:
    img = np.expand_dims(img, axis=0)

model_crop.predict(img)
"""Lỗi"""
tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node model/conv2d/Conv2D (defined at custom.py:81) ]] [Op:__inference_predict_function_18773]
"""

Cho em hỏi có cách nào load model Crop với Dect bình thường để test ko ạ? Hoặc cách khắc phụ lỗi ở trên. Em cảm ơn ạ.

**Comment by phuhung273** [comment]
Hình như là bạn cài cuda, cudnn chưa đúng ấy. Nếu cài cuda đúng có thể test bình thường ko cần tensorflow serving nhé.

**Comment by phamvanhanh6720** [comment]
Bạn clone lại nhé. Mình fix rồi
